# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimationPractice_BeerList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimationPractice_BeerList
pod 'SDWebImage', '~> 4.0'
end
