# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NagMaker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BusyNavigationBar', '~> 2.0'
  pod 'UIView+Shake', '~> 1.3'

  # Pods for NagMaker

end
