# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'TimeCapslets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'JSSAlertView', '~> 3.0'
  # Pods for TimeCapslets

end
