# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'OpenSourcePhotoPickerPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for OpenSourcePhotoPickerPractice

pod 'ImagePicker'
pod 'TLPhotoPicker', '~> 1.1'

end
