# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'UIImagePickerPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for TLPhotoPickerExample
  pod ‘TLPhotoPicker’, ‘~> 1.1’
  pod 'ImagePicker', '~> 2.1'


end
